config/routes.rb
Rails.application.routes.draw do
  # get 'fremars/index'
  # get 'fremars/show'
  # get 'fremars/new'
  # get 'fremars/edit'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'fremars#index'
  resources :fremars
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/fremar.rb
class Fremar < ApplicationRecord
  has_one_attached :image
  validates :name, presence: true, length: { maximum: 50 }
  validates :seller, presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 50 }
  validates :price, presence: true,
    numericality: { 
      only_integer: true,
      greater_than: 1
    }
  validates :description, presence: true, length: { maximum: 1000 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/fremars_controller.rb
class FremarsController < ApplicationController
  before_action :set_fremar, only: [:show, :edit, :update, :destroy]

  def index
    @fremars = Fremar.all
  end

  def show
    # @fremar = Fremar.find(params[:id])
  end

  def new
    @fremar = Fremar.new
  end

  def edit
    # @fremar = Fremar.find(params[:id])
  end

  def update
    @fremar.update(fremar_params)
    if @fremar.save
      redirect_to fremars_url, notice: "#{@fremar.name}を更新しました｡"
    else
      render :edit
    end   
  end

  def create
    @fremar = Fremar.new(fremar_params)
    if @fremar.save
      redirect_to @fremar, notice: "#{@fremar.name}を登録しました｡"
    else
      render :new
    end
  end

  def destroy
    @fremar.destroy
    redirect_to fremars_url, notice: "#{@fremar.name}を削除しました｡"
  end
  
  private 

  def fremar_params
    params.require(:fremar).permit(:name, :price, :seller, :description, :email, :image)
  end

  def set_fremar
    @fremar = Fremar.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fremars_helper.rb
module FremarsHelper
end

app/views/fremars/_form.html.slim
- if fremar.errors.present?
  ul#error_explanation
    - fremar.errors.full_messages.each do |message|
      li= message

= form_with model: @fremar, local: true do |f|
  .form-group
    = f.label :name
    = f.text_field :name, class: 'form-control', id: 'fremar_name'
  .form-group
    = f.label :description
    = f.text_area :description, rows: 5, class: 'form-control', id: 'fremar_descrition'
  .form-group
    = f.label :price
    = f.text_field :price, class: 'form-control', id: 'fremar_price'
  .form-group
    = f.label :seller
    = f.text_field :seller, class: 'form-control', id: 'fremar_seller'
  .form-group
    = f.label :email
    = f.text_field :email, class: 'form-control', id: 'fremar_email'
  .form-group
    = f.label :image
    = f.file_field :image, row: 5, class: 'form-control'
  = f.submit nil, class: 'btn btn-primary'

app/views/fremars/edit.html.slim
h1 登録商品の編集

= render partial: 'form', locals: { fremar: @fremar }

br
  .nav.justify-content-expand
    = link_to '商品一覧', fremars_path, class: 'btn btn-primary'

app/views/fremars/index.html.slim
h1 出品商品一覧
= link_to '商品出品', new_fremar_path, class: 'btn btn-primary'

.mb-3
table.table.table-hover
  thead.thead-default
    tr
      th= Fremar.human_attribute_name(:name)
      th= Fremar.human_attribute_name(:created_at)
      th
  tbody
    - @fremars.each do |fremar|
      tr
        td= link_to fremar.name, fremar
        td= fremar.created_at
        td
          = link_to '編集', edit_fremar_path(fremar), class: 'btn btn-primary mr-3'
          = link_to '削除', fremar, method: :delete, data: { confirm: "#{fremar.name}を削除します｡よろしいですか？" },
          class: 'btn btn-danger'

app/views/fremars/new.html.slim
h1 出品商品登録

= render partial: 'form', locals: { fremar: @fremar }

br
  .nav.justify-content-expand
    = link_to '商品一覧', fremars_path, class: 'btn btn-primary'

app/views/fremars/show.html.slim
h1 商品詳細

table.table.table-hover
  tbody
    tr
      th= Fremar.human_attribute_name(:id)
      td= @fremar.id
    tr
      th= Fremar.human_attribute_name(:name)
      td= @fremar.name
    tr
      th= Fremar.human_attribute_name(:price)
      td= @fremar.price
    tr
      th= Fremar.human_attribute_name(:description)
      td= simple_format(h(@fremar.description), {}, sanitize: false, wrapper_tag: "div")
    tr
      th= Fremar.human_attribute_name(:image)
      td= image_tag @fremar.image if @fremar.image.attached?
    tr
      th= Fremar.human_attribute_name(:seller)
      td= @fremar.seller
    tr
      th= Fremar.human_attribute_name(:email)
      td= @fremar.email
    tr
      th= Fremar.human_attribute_name(:created_at)
      td= @fremar.created_at
    tr
      th= Fremar.human_attribute_name(:updated_at)
      td= @fremar.updated_at
br
  .nav.justify-content-expand
    = link_to '商品一覧', fremars_path, class: 'btn btn-primary'

= link_to '編集', edit_fremar_path, class: 'btn btn-primary mr-3'
= link_to '削除', @fremar, method: :delete, data: { confirm: "#{@fremar.name}を削除します｡よろしいですか？" },
          class: 'btn btn-danger'

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | FreeMarketStore
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  body
    .app-title.navbar-expand-md.navbar-light.bg-light
      .navbar-brand freemarke
    .container 
      - if flash.notice.present?
        .alert.alert-success= flash.notice
      = yield